config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :users
  
  root to: "posts#index"
    get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts do
  resources :comments
 	end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	include Visible
  
  attr_accessor :content, :name, :tag_list
  has_many :taggings
  has_many :tags, through: :taggings

	belongs_to :user
	has_many :comments, dependent: :destroy


	has_many_attached :files do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
	has_one_attached :image
  has_rich_text :content

  VALID_STATUSES = ['public', 'private', 'archived']

  validates :status, inclusion: { in: VALID_STATUSES }

 	def archived?
    status == 'archived'
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end
  
  def tag_list
    tags.map(&:name).join(", ")
  end
  
  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "123", password: "qwe", except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
    @posts = Post.tagged_with(params[:tag])
    else
    @posts = Post.all.with_rich_text_content
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
   def post_params
     params.require(:post).permit(:title, :subtitle, :lead, :tag_list, :content, :image, :user_id, :status, files: [] )
   end




end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this   post from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>
  <div class="field">    
    <%= form.label :files %>
    <%= form.file_field :files, multiple: true, direct_upload: true, class: 'form-control' %>
  </div>
  <div class="field">    
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="field">
  <%= form.label :tag_list, "Tags (separated by commas)" %><br />
  <%= form.text_field :tag_list %>
</div>
  <div class="field">
    <%= form.label :lead %>
    <%= form.text_field :lead %>
  </div>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>
  <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>
  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Posts</h1>
Our blog has <%= Post.public_count %> articles and counting!

<table>
  <thead>
    <tr>

      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>

<div id="tag_cloud">
  <% tag_cloud Post.tag_counts, %w{s m l} do |tags, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

    <% @posts.each do |post| %>
      <% unless post.archived? %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.subtitle %></td>
        <td><%= post.lead %></td>
<!--         <td><%= post.image.metadata %></td> -->
        <td><%= image_tag(post.image.variant(resize: "250x200^")) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     <% end %>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<h2>
  <strong></strong></h2>
<h1>
  <strong></strong>
  <%= @post.title %>
</h1>
<h2>
  <strong></strong>
  <%= @post.subtitle %>
</h2>
<h3>
  <strong></strong>
  <%= @post.lead %>
</h3>
<h3>
  <strong>Author:</strong>
  <%= link_to @post.user.name, @post.user%>
</h3>

<!--       <td><%= @post.image.metadata %></td> -->
      <td><%= image_tag(@post.image.variant(resize: "1100x700^")) %></td>

 <p>Tags: <%= @post.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></p>
  <strong></strong>
  <%= @post.content %>
</p>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>